MujocoPlugins:
  - type: mujoco_ros_control/MujocoRosControlPlugin
    hardware:
      type: franka_mujoco/FrankaHWSim
      control_period: 0.001
      robot_description: robot_description
      arm_id: left
    robot_namespace: left
  - type: mujoco_ros_control/MujocoRosControlPlugin
    hardware:
      type: franka_mujoco/FrankaHWSim
      control_period: 0.001
      robot_description: robot_description
      arm_id: right
    robot_namespace: right